


version: '3.8'




services: 

  # fastapi:
  #   container_name: "fastapi_web"
  #   image: ./DOCKERFILE
  #   restart: always

  mongodb: 
    container_name: "mongodb"
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo_network
    

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
     - mongodb
    networks:
      - mongo_network
networks:
    mongo_network: {}
volumes:
  db:
  configdb:


